create table [dbo].[Resources] (
    [Culture] varchar (10)    not null,
    [Name]    varchar (100)   not null,
    [Value]   nvarchar (4000) not null,
    constraint [pk_culture_name] primary key clustered ([Culture] asc, [Name] asc)
);

go

-- Arabic
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'AddPerson', N'إضافة شخص')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'Age', N'العمر')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'AgeRange', N'يجب أن يكون بين 10 و 130')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'AgeRequired', N'أدخل العمر')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'Biography', N'السيرة')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'ChooseYourLanguage', N'اختر اللغة')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'Create', N'إنشاء')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'Email', N'البريد الإلكتروني')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'EmailInvalid', N'البريد الإلكتروني غير صحيح')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'EmailRequired', N'أدخل البريد الإلكتروني')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'FirstName', N'الإسم')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'FirstNameLong', N'يجب أن يكون أقل من 50 حرف')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'FirstNameRequired', N'أدخل الإسم')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'LastName', N'إسم العائلة')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'LastNameLong', N'يجب أن يكون أقل من 50 حرف')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'LastNameRequired', N'أدخل إسم العائلة')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'LogOff', N'تسجيل خروج')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'LogOn', N'تسجيل دخول')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ar', N'Register', N'تسجيل')


-- English
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'AddPerson', N'Add person')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'Age', N'Age')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'AgeRange', N'Must be between 10 and 130')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'AgeRequired', N'Age is required')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'Biography', N'Biography')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'ChooseYourLanguage', N'Choose your language')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'Create', N'Create')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'Email', N'Email')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'EmailInvalid', N'Email is not valid')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'EmailRequired', N'Email is required')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'FirstName', N'First name')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'FirstNameLong', N'Must be less than 50 characters')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'FirstNameRequired', N'First name is required')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'LastName', N'Last name')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'LastNameLong', N'Must be less than 50 characters')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'LastNameRequired', N'Last name is required')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'LogOff', N'Log off')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'LogOn', N'Log on')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'en-us', N'Register', N'Register')

-- Spanish
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'AddPerson', N'Ingresar persona')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'Age', N'Edad')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'AgeRange', N'Debe ser entre 10 y 130')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'AgeRequired', N'Debe ingresar su edad')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'Biography', N'Biografía')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'ChooseYourLanguage', N'Elige su idioma')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'Create', N'Crear')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'Email', N'Correo electrónico')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'EmailInvalid', N'El correo electrónico ingresado no es válido')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'EmailRequired', N'Debe ingresar su correo electrónico')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'FirstName', N'Primer nombre')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'FirstNameLong', N'Debe ser menos de 50 caracteres')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'FirstNameRequired', N'Debe ingresar su nombre')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'LastName', N'Apellido')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'LastNameLong', N'Debe ser menos de 50 caracteres')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'LastNameRequired', N'Debe ingresar su apellido')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'LogOff', N'Cerrar sesión')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'LogOn', N'Iniciar sesión')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'es', N'Register', N'Registrar')

-- Chinese Traditional
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'AddPerson', N'添加人')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'Age', N'年齡')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'AgeRange', N'必須介於10和130')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'AgeRequired', N'年齡要求')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'Biography', N'傳記')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'ChooseYourLanguage', N'選擇你的語言')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'Create', N'創建')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'Email', N'電子郵件')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'EmailInvalid', N'電子郵件是無效')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'EmailRequired', N'電子郵件是必需的')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'FirstName', N'名字')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'FirstNameLong', N'必須少於50個字符')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'FirstNameRequired', N'第一個名字是必需的')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'LastName', N'姓')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'LastNameLong', N'必須少於50個字符')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'LastNameRequired', N'姓氏是必需的')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'LogOff', N'註銷')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'LogOn', N'登錄')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'zh-CN', N'Register', N'註冊')


--Tamil (India)
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'AddPerson', N'व्यक्ति जोड़ें')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'Age', N'आयु')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'AgeRange', N'10 और 130 के बीच होना चाहिए')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'AgeRequired', N'आयु की आवश्यकता है')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'Biography', N'जीवनी')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'ChooseYourLanguage', N'अपनी भाषा चुनें')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'Create', N'बनाएँ')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'Email', N'ईमेल')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'EmailInvalid', N'विद्युतडाक मान्य नहीं है')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'EmailRequired', N'ईमेल की जरूरत है')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'FirstName', N'पहला नाम')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'FirstNameLong', N'कम से कम 50 अक्षरों का होना चाहिए')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'FirstNameRequired', N'पहला नाम आवश्यक है')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'LastName', N'उपनाम')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'LastNameLong', N'कम से कम 50 अक्षरों का होना चाहिए')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'LastNameRequired', N'अंतिम नाम के लिए आवश्यक है')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'LogOff', N'लॉग ऑफ़')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'LogOn', N'पर लॉग ऑन करें')
INSERT INTO [dbo].[Resources] ([Culture], [Name], [Value]) VALUES (N'ta', N'Register', N'रजिस्टर')