CREATE TABLE [dbo].[Style] (
    [MerretStyleID]         INT             IDENTITY (1, 1) NOT NULL,
    [MerretDescription]     VARCHAR (30)    NOT NULL,
    [DepartmentID]          INT             NULL,
    [BrandID]               VARCHAR (10)    NULL,
    [WebAttribute1]         CHAR (3)        NULL,
    [WebAttribute2]         CHAR (3)        NULL,
    [WebAttribute3]         CHAR (3)        NULL,
    [WebAttribute4]         CHAR (3)        NULL,
    [WebAttribute5]         CHAR (3)        NULL,
    [WebAttribute6]         CHAR (3)        NULL,
    [WebAttribute7]         CHAR (3)        NULL,
    [WebAttribute8]         CHAR (3)        NULL,
    [WebAttribute9]         CHAR (3)        NULL,
    [WebAttribute10]        CHAR (3)        NULL,
    [ShortWebDescription]   VARCHAR (70)    NULL,
    [LongWebDescription]    VARCHAR (1500)  NULL,
    [StyleTemplateID]       INT             NULL,
    [Live]                  BIT             NOT NULL,
    [MinPrice]              DECIMAL (18, 2) NULL,
    [MaxPrice]              DECIMAL (18, 2) NULL,
    [OverrideMerretVAT]     BIT             NULL,
    [VAT]                   DECIMAL (18, 2) NULL,
    [StyleType]             INT             NULL,
    [ExtendedProductDetail] TEXT            NOT NULL,
    [GradeID]               SMALLINT        NULL,
    [HasImage]              BIT             NULL,
    [BucketID]              INT             NOT NULL,
    [Season]                CHAR (4)        NULL,
    [WebApplicable]         VARCHAR (2)     NULL,
    [IsMatrix]              BIT             NULL,
    [IsHamper]              BIT             NOT NULL,
    [HasGiftBox]            BIT             NOT NULL,
    [EnabledMagento]        BIT             NULL,
    [MarkedDown]            BIT             NOT NULL,
    [MagentoID]             INT             NULL,
    [MaxItemsBasket]        INT             NULL,
    [IsCategoryDirty]       BIT             NULL,
    [EditorsView]           VARCHAR (750)   NOT NULL,
    [InStoreOnly]           BIT             NULL,
    [GroupColourOptions]    BIT             NULL,
    [IsSeasonal]            BIT             NULL,
    [SizeGuideID]           INT             NULL,
    [DeliveryInfoID]        INT             NULL,
    [MerchandiseBrandID]    INT             NULL,
    [IsDirty]               BIT             NOT NULL,
    [IsMerretDirty]         BIT             NOT NULL,
    [Over18Only]            BIT             NOT NULL,
    [MagentoPrice]          DECIMAL (10, 2) NULL,
    [TaxClassID]            INT             NULL,
    [FamilyBusiness]        VARCHAR (3)     NULL,
    [IsFashion]             BIT             NULL,
    [LastImportedDate]      DATETIME        NULL,
    [ImportedToGAE]         BIT             NOT NULL,
    [ImageImportedToGAE]    BIT             NOT NULL,
    [FirstEnabled]          DATETIME        NULL,
    [IsMerretMatrix]        BIT             NULL,
    [IsColourOnly]          BIT             NULL,
    [InconsistentPrice]     BIT             NULL,
    [ProductLink]           VARCHAR (500)   NULL,
    [AutomaticStock]        BIT             NULL,
    [ProductLinkingDone]    BIT             NULL,
    [RequestedGoLiveDate]   DATETIME        NULL,
    [EmailWhenLive]         VARCHAR (300)   NULL,
    [ClickToPurchase]       BIT             NULL,
    [VersionNumber]         INT             NOT NULL,
    [StyledWith]            BIT             NULL,
    [PIMStyleID]            VARCHAR (10)    NULL,
    [ClickTry]              BIT             NULL,
    [IncludeInFeed]         BIT             NULL,
    [SizeTypeID]            INT             NULL,
    CONSTRAINT [PK_Style] PRIMARY KEY CLUSTERED ([MerretStyleID] ASC)
);

